version = 1

test_patterns = ["**/.*test.*"]

exclude_patterns = ["docs/**"]

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = [
    "nodejs",
    "vitest",
    "browser"
  ]

[[transformers]]
name = "prettier"
